apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-eureka-server
  labels:
    app: cloud-eureka
spec:
  selector:
    matchLabels:
      app: cloud-eureka
  template:
    metadata:
      labels:
        app: cloud-eureka
    spec:
      containers:
      - name: cloud-eureka-container
        image: docker.io/lohitesh/cloud-eureka-service
        ports: 
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-eureka-services
spec:
  type: NodePort
  ports:
  - nodePort: 32007
    port: 8761
    targetPort: 8761
  selector:
    app: cloud-eureka
